# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6d872547e7ee921402b11fb6c30a65b25bcc0776e405448a9e30fa14a873577a82ba1ad21c69026bbeacd4c9aa3031bc77de491dcc87877336963f4a736f6cf

test:
  secret_key_base: 2247fb4bca5bc4293bf61a5dff24530978af148ee33671c66750c206b1fcfa63860aec634a69f72432b5aa5e70d5687646c57ceb32f38f91f4c36a4adf4fe8c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
